/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { postRequestDtoSchema } from "./postRequestDtoSchema.ts";
import { postResponseDtoSchema } from "./postResponseDtoSchema.ts";
import { z } from "zod/v4";

/**
 * @description Created
 */
export const create201Schema = z.lazy(() => postResponseDtoSchema)

export const createMutationRequestSchema = z.lazy(() => postRequestDtoSchema)

export const createMutationResponseSchema = z.lazy(() => create201Schema)