/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";
import { memberRequestDtoSchema } from "./memberRequestDtoSchema.ts";
import { memberResponseDtoSchema } from "./memberResponseDtoSchema.ts";

/**
 * @description Created
 */
export const create1201Schema = z.lazy(() => memberResponseDtoSchema);

export const create1MutationRequestSchema = z.lazy(
	() => memberRequestDtoSchema,
);

export const create1MutationResponseSchema = z.lazy(() => create1201Schema);
