/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const delete1PathParamsSchema = z.object({
	id: z.coerce.number().int(),
});

/**
 * @description No Content
 */
export const delete1204Schema = z.any();

export const delete1MutationResponseSchema = z.lazy(() => delete1204Schema);
