/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const deletePathParamsSchema = z.object({
	id: z.coerce.number().int(),
});

/**
 * @description No Content
 */
export const delete204Schema = z.any();

export const deleteMutationResponseSchema = z.lazy(() => delete204Schema);
