/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";
import { postResponseDtoSchema } from "./postResponseDtoSchema.ts";

export const findByIdPathParamsSchema = z.object({
	id: z.coerce.number().int(),
});

/**
 * @description OK
 */
export const findById200Schema = z.lazy(() => postResponseDtoSchema);

export const findByIdQueryResponseSchema = z.lazy(() => findById200Schema);
