/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";
import { memberResponseDtoSchema } from "./memberResponseDtoSchema.ts";

export const findById1PathParamsSchema = z.object({
	id: z.coerce.number().int(),
});

/**
 * @description OK
 */
export const findById1200Schema = z.lazy(() => memberResponseDtoSchema);

export const findById1QueryResponseSchema = z.lazy(() => findById1200Schema);
