/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { memberResponseDtoSchema } from "./memberResponseDtoSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const findAll1200Schema = z.array(z.lazy(() => memberResponseDtoSchema))

export const findAll1QueryResponseSchema = z.lazy(() => findAll1200Schema)