/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";
import { postResponseDtoSchema } from "./postResponseDtoSchema.ts";

/**
 * @description OK
 */
export const findAll200Schema = z.array(z.lazy(() => postResponseDtoSchema));

export const findAllQueryResponseSchema = z.lazy(() => findAll200Schema);
