/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const memberResponseDtoSchema = z.object({
	id: z.optional(z.int()),
	name: z.optional(z.string()),
	email: z.optional(z.string()),
});
