/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const memberRequestDtoSchema = z.object({
	name: z.string().min(1),
	email: z.email().min(1),
});
