/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const notificationDtoSchema = z.object({
	id: z.optional(z.int()),
	message: z.optional(z.string()),
	createdAt: z.optional(z.iso.datetime()),
});
