/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";
import { notificationDtoSchema } from "./notificationDtoSchema.ts";

export const pollQueryParamsSchema = z.object({
	lastId: z.coerce.number().int().default(0),
});

/**
 * @description OK
 */
export const poll200Schema = z.array(z.lazy(() => notificationDtoSchema));

export const pollQueryResponseSchema = z.lazy(() => poll200Schema);
