/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const postRequestDtoSchema = z.object({
	title: z.string().min(1),
	content: z.optional(z.string()),
	author: z.optional(z.string()),
});
