/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const postResponseDtoSchema = z.object({
	id: z.optional(z.int()),
	title: z.optional(z.string()),
	content: z.optional(z.string()),
	author: z.optional(z.string()),
	createdAt: z.optional(z.iso.datetime()),
	updatedAt: z.optional(z.iso.datetime()),
});
