/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { notificationDtoSchema } from "./notificationDtoSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const publish200Schema = z.lazy(() => notificationDtoSchema)

export const publishMutationRequestSchema = z.object({
    
    }).catchall(z.string())

export const publishMutationResponseSchema = z.lazy(() => publish200Schema)