/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { sseEmitterSchema } from "./sseEmitterSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const subscribe200Schema = z.lazy(() => sseEmitterSchema)

export const subscribeQueryResponseSchema = z.lazy(() => subscribe200Schema)