/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";
import { memberRequestDtoSchema } from "./memberRequestDtoSchema.ts";
import { memberResponseDtoSchema } from "./memberResponseDtoSchema.ts";

export const update1PathParamsSchema = z.object({
	id: z.coerce.number().int(),
});

/**
 * @description OK
 */
export const update1200Schema = z.lazy(() => memberResponseDtoSchema);

export const update1MutationRequestSchema = z.lazy(
	() => memberRequestDtoSchema,
);

export const update1MutationResponseSchema = z.lazy(() => update1200Schema);
