/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";
import { postRequestDtoSchema } from "./postRequestDtoSchema.ts";
import { postResponseDtoSchema } from "./postResponseDtoSchema.ts";

export const updatePathParamsSchema = z.object({
	id: z.coerce.number().int(),
});

/**
 * @description OK
 */
export const update200Schema = z.lazy(() => postResponseDtoSchema);

export const updateMutationRequestSchema = z.lazy(() => postRequestDtoSchema);

export const updateMutationResponseSchema = z.lazy(() => update200Schema);
