/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CreateMutationRequest, CreateMutationResponse } from "../models/Create.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createMutationKey = () => [{ url: '/api/posts' }] as const

export type CreateMutationKey = ReturnType<typeof createMutationKey>

/**
 * @summary 게시글 생성
 * {@link /api/posts}
 */
export async function create(data: CreateMutationRequest, config: Partial<RequestConfig<CreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<CreateMutationResponse, ResponseErrorConfig<Error>, CreateMutationRequest>({ method : "POST", url : `/api/posts`, data : requestData, ... requestConfig })
  return res.data
}

export function createMutationOptions<TContext = unknown>(config: Partial<RequestConfig<CreateMutationRequest>> & { client?: typeof fetch } = {}) {

        const mutationKey = createMutationKey()
        return mutationOptions<CreateMutationResponse, ResponseErrorConfig<Error>, {data: CreateMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return create(data, config)
          },
        })

}

/**
 * @summary 게시글 생성
 * {@link /api/posts}
 */
export function useCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateMutationResponse, ResponseErrorConfig<Error>, {data: CreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? createMutationKey()

          const baseOptions = createMutationOptions(config) as UseMutationOptions<CreateMutationResponse, ResponseErrorConfig<Error>, {data: CreateMutationRequest}, TContext>
          

          return useMutation<CreateMutationResponse, ResponseErrorConfig<Error>, {data: CreateMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<CreateMutationResponse, ResponseErrorConfig<Error>, {data: CreateMutationRequest}, TContext>
      
}