/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import type {
	Create1MutationRequest,
	Create1MutationResponse,
} from "../models/Create1.ts";

export const create1MutationKey = () => [{ url: "/api/members" }] as const;

export type Create1MutationKey = ReturnType<typeof create1MutationKey>;

/**
 * @summary 회원 생성
 * {@link /api/members}
 */
export async function create1(
	data: Create1MutationRequest,
	config: Partial<RequestConfig<Create1MutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		Create1MutationResponse,
		ResponseErrorConfig<Error>,
		Create1MutationRequest
	>({
		method: "POST",
		url: `/api/members`,
		data: requestData,
		...requestConfig,
	});
	return res.data;
}

export function create1MutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<Create1MutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const mutationKey = create1MutationKey();
	return mutationOptions<
		Create1MutationResponse,
		ResponseErrorConfig<Error>,
		{ data: Create1MutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return create1(data, config);
		},
	});
}

/**
 * @summary 회원 생성
 * {@link /api/members}
 */
export function useCreate1<TContext>(
	options: {
		mutation?: UseMutationOptions<
			Create1MutationResponse,
			ResponseErrorConfig<Error>,
			{ data: Create1MutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig<Create1MutationRequest>> & {
			client?: typeof fetch;
		};
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey = mutationOptions.mutationKey ?? create1MutationKey();

	const baseOptions = create1MutationOptions(config) as UseMutationOptions<
		Create1MutationResponse,
		ResponseErrorConfig<Error>,
		{ data: Create1MutationRequest },
		TContext
	>;

	return useMutation<
		Create1MutationResponse,
		ResponseErrorConfig<Error>,
		{ data: Create1MutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		Create1MutationResponse,
		ResponseErrorConfig<Error>,
		{ data: Create1MutationRequest },
		TContext
	>;
}
