/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import type {
	Delete1MutationResponse,
	Delete1PathParams,
} from "../models/Delete1.ts";

export const delete1MutationKey = () => [{ url: "/api/members/:id" }] as const;

export type Delete1MutationKey = ReturnType<typeof delete1MutationKey>;

/**
 * @summary 회원 삭제
 * {@link /api/members/:id}
 */
export async function delete1(
	id: Delete1PathParams["id"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		Delete1MutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "DELETE", url: `/api/members/${id}`, ...requestConfig });
	return res.data;
}

export function delete1MutationOptions<TContext = unknown>(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const mutationKey = delete1MutationKey();
	return mutationOptions<
		Delete1MutationResponse,
		ResponseErrorConfig<Error>,
		{ id: Delete1PathParams["id"] },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id }) => {
			return delete1(id, config);
		},
	});
}

/**
 * @summary 회원 삭제
 * {@link /api/members/:id}
 */
export function useDelete1<TContext>(
	options: {
		mutation?: UseMutationOptions<
			Delete1MutationResponse,
			ResponseErrorConfig<Error>,
			{ id: Delete1PathParams["id"] },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey = mutationOptions.mutationKey ?? delete1MutationKey();

	const baseOptions = delete1MutationOptions(config) as UseMutationOptions<
		Delete1MutationResponse,
		ResponseErrorConfig<Error>,
		{ id: Delete1PathParams["id"] },
		TContext
	>;

	return useMutation<
		Delete1MutationResponse,
		ResponseErrorConfig<Error>,
		{ id: Delete1PathParams["id"] },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		Delete1MutationResponse,
		ResponseErrorConfig<Error>,
		{ id: Delete1PathParams["id"] },
		TContext
	>;
}
