/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import type {
	DeleteMutationResponse,
	DeletePathParams,
} from "../models/Delete.ts";

export const deleteMutationKey = () => [{ url: "/api/posts/:id" }] as const;

export type DeleteMutationKey = ReturnType<typeof deleteMutationKey>;

/**
 * @summary 게시글 삭제
 * {@link /api/posts/:id}
 */
export async function _delete(
	id: DeletePathParams["id"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		DeleteMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "DELETE", url: `/api/posts/${id}`, ...requestConfig });
	return res.data;
}

export function deleteMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const mutationKey = deleteMutationKey();
	return mutationOptions<
		DeleteMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: DeletePathParams["id"] },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id }) => {
			return _delete(id, config);
		},
	});
}

/**
 * @summary 게시글 삭제
 * {@link /api/posts/:id}
 */
export function useDelete<TContext>(
	options: {
		mutation?: UseMutationOptions<
			DeleteMutationResponse,
			ResponseErrorConfig<Error>,
			{ id: DeletePathParams["id"] },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey = mutationOptions.mutationKey ?? deleteMutationKey();

	const baseOptions = deleteMutationOptions(config) as UseMutationOptions<
		DeleteMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: DeletePathParams["id"] },
		TContext
	>;

	return useMutation<
		DeleteMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: DeletePathParams["id"] },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		DeleteMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: DeletePathParams["id"] },
		TContext
	>;
}
