/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import type { FindAll1QueryResponse } from "../models/FindAll1.ts";

export const findAll1QueryKey = () => [{ url: "/api/members" }] as const;

export type FindAll1QueryKey = ReturnType<typeof findAll1QueryKey>;

/**
 * @summary 전체 회원 조회
 * {@link /api/members}
 */
export async function findAll1(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		FindAll1QueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: `/api/members`, ...requestConfig });
	return res.data;
}

export function findAll1QueryOptions(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = findAll1QueryKey();
	return queryOptions<
		FindAll1QueryResponse,
		ResponseErrorConfig<Error>,
		FindAll1QueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return findAll1(config);
		},
	});
}

/**
 * @summary 전체 회원 조회
 * {@link /api/members}
 */
export function useFindAll1<
	TData = FindAll1QueryResponse,
	TQueryData = FindAll1QueryResponse,
	TQueryKey extends QueryKey = FindAll1QueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				FindAll1QueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? findAll1QueryKey();

	const query = useQuery(
		{
			...findAll1QueryOptions(config),
			queryKey,
			...queryOptions,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
