/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import type { FindAll1QueryResponse } from "../models/FindAll1.ts";

export const findAll1SuspenseQueryKey = () =>
	[{ url: "/api/members" }] as const;

export type FindAll1SuspenseQueryKey = ReturnType<
	typeof findAll1SuspenseQueryKey
>;

/**
 * @summary 전체 회원 조회
 * {@link /api/members}
 */
export async function findAll1Suspense(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		FindAll1QueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: `/api/members`, ...requestConfig });
	return res.data;
}

export function findAll1SuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = findAll1SuspenseQueryKey();
	return queryOptions<
		FindAll1QueryResponse,
		ResponseErrorConfig<Error>,
		FindAll1QueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return findAll1Suspense(config);
		},
	});
}

/**
 * @summary 전체 회원 조회
 * {@link /api/members}
 */
export function useFindAll1Suspense<
	TData = FindAll1QueryResponse,
	TQueryKey extends QueryKey = FindAll1SuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				FindAll1QueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? findAll1SuspenseQueryKey();

	const query = useSuspenseQuery(
		{
			...findAll1SuspenseQueryOptions(config),
			queryKey,
			...queryOptions,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
