/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import type {
	FindById1PathParams,
	FindById1QueryResponse,
} from "../models/FindById1.ts";

export const findById1SuspenseQueryKey = (id: FindById1PathParams["id"]) =>
	[{ url: "/api/members/:id", params: { id: id } }] as const;

export type FindById1SuspenseQueryKey = ReturnType<
	typeof findById1SuspenseQueryKey
>;

/**
 * @summary 회원 단건 조회
 * {@link /api/members/:id}
 */
export async function findById1Suspense(
	id: FindById1PathParams["id"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		FindById1QueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: `/api/members/${id}`, ...requestConfig });
	return res.data;
}

export function findById1SuspenseQueryOptions(
	id: FindById1PathParams["id"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = findById1SuspenseQueryKey(id);
	return queryOptions<
		FindById1QueryResponse,
		ResponseErrorConfig<Error>,
		FindById1QueryResponse,
		typeof queryKey
	>({
		enabled: !!id,
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return findById1Suspense(id, config);
		},
	});
}

/**
 * @summary 회원 단건 조회
 * {@link /api/members/:id}
 */
export function useFindById1Suspense<
	TData = FindById1QueryResponse,
	TQueryKey extends QueryKey = FindById1SuspenseQueryKey,
>(
	id: FindById1PathParams["id"],
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				FindById1QueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? findById1SuspenseQueryKey(id);

	const query = useSuspenseQuery(
		{
			...findById1SuspenseQueryOptions(id, config),
			queryKey,
			...queryOptions,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
