/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import type { FindAllQueryResponse } from "../models/FindAll.ts";

export const findAllQueryKey = () => [{ url: "/api/posts" }] as const;

export type FindAllQueryKey = ReturnType<typeof findAllQueryKey>;

/**
 * @summary 전체 게시글 조회
 * {@link /api/posts}
 */
export async function findAll(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		FindAllQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: `/api/posts`, ...requestConfig });
	return res.data;
}

export function findAllQueryOptions(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = findAllQueryKey();
	return queryOptions<
		FindAllQueryResponse,
		ResponseErrorConfig<Error>,
		FindAllQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return findAll(config);
		},
	});
}

/**
 * @summary 전체 게시글 조회
 * {@link /api/posts}
 */
export function useFindAll<
	TData = FindAllQueryResponse,
	TQueryData = FindAllQueryResponse,
	TQueryKey extends QueryKey = FindAllQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				FindAllQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? findAllQueryKey();

	const query = useQuery(
		{
			...findAllQueryOptions(config),
			queryKey,
			...queryOptions,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
