/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import type {
	FindByIdPathParams,
	FindByIdQueryResponse,
} from "../models/FindById.ts";

export const findByIdQueryKey = (id: FindByIdPathParams["id"]) =>
	[{ url: "/api/posts/:id", params: { id: id } }] as const;

export type FindByIdQueryKey = ReturnType<typeof findByIdQueryKey>;

/**
 * @summary 게시글 단건 조회
 * {@link /api/posts/:id}
 */
export async function findById(
	id: FindByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		FindByIdQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: `/api/posts/${id}`, ...requestConfig });
	return res.data;
}

export function findByIdQueryOptions(
	id: FindByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = findByIdQueryKey(id);
	return queryOptions<
		FindByIdQueryResponse,
		ResponseErrorConfig<Error>,
		FindByIdQueryResponse,
		typeof queryKey
	>({
		enabled: !!id,
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return findById(id, config);
		},
	});
}

/**
 * @summary 게시글 단건 조회
 * {@link /api/posts/:id}
 */
export function useFindById<
	TData = FindByIdQueryResponse,
	TQueryData = FindByIdQueryResponse,
	TQueryKey extends QueryKey = FindByIdQueryKey,
>(
	id: FindByIdPathParams["id"],
	options: {
		query?: Partial<
			QueryObserverOptions<
				FindByIdQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? findByIdQueryKey(id);

	const query = useQuery(
		{
			...findByIdQueryOptions(id, config),
			queryKey,
			...queryOptions,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
