/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import type { FindAllQueryResponse } from "../models/FindAll.ts";

export const findAllSuspenseQueryKey = () => [{ url: "/api/posts" }] as const;

export type FindAllSuspenseQueryKey = ReturnType<
	typeof findAllSuspenseQueryKey
>;

/**
 * @summary 전체 게시글 조회
 * {@link /api/posts}
 */
export async function findAllSuspense(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		FindAllQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: `/api/posts`, ...requestConfig });
	return res.data;
}

export function findAllSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = findAllSuspenseQueryKey();
	return queryOptions<
		FindAllQueryResponse,
		ResponseErrorConfig<Error>,
		FindAllQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return findAllSuspense(config);
		},
	});
}

/**
 * @summary 전체 게시글 조회
 * {@link /api/posts}
 */
export function useFindAllSuspense<
	TData = FindAllQueryResponse,
	TQueryKey extends QueryKey = FindAllSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				FindAllQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? findAllSuspenseQueryKey();

	const query = useSuspenseQuery(
		{
			...findAllSuspenseQueryOptions(config),
			queryKey,
			...queryOptions,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
