/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import type {
	FindByIdPathParams,
	FindByIdQueryResponse,
} from "../models/FindById.ts";

export const findByIdSuspenseQueryKey = (id: FindByIdPathParams["id"]) =>
	[{ url: "/api/posts/:id", params: { id: id } }] as const;

export type FindByIdSuspenseQueryKey = ReturnType<
	typeof findByIdSuspenseQueryKey
>;

/**
 * @summary 게시글 단건 조회
 * {@link /api/posts/:id}
 */
export async function findByIdSuspense(
	id: FindByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		FindByIdQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: `/api/posts/${id}`, ...requestConfig });
	return res.data;
}

export function findByIdSuspenseQueryOptions(
	id: FindByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = findByIdSuspenseQueryKey(id);
	return queryOptions<
		FindByIdQueryResponse,
		ResponseErrorConfig<Error>,
		FindByIdQueryResponse,
		typeof queryKey
	>({
		enabled: !!id,
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return findByIdSuspense(id, config);
		},
	});
}

/**
 * @summary 게시글 단건 조회
 * {@link /api/posts/:id}
 */
export function useFindByIdSuspense<
	TData = FindByIdQueryResponse,
	TQueryKey extends QueryKey = FindByIdSuspenseQueryKey,
>(
	id: FindByIdPathParams["id"],
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				FindByIdQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? findByIdSuspenseQueryKey(id);

	const query = useSuspenseQuery(
		{
			...findByIdSuspenseQueryOptions(id, config),
			queryKey,
			...queryOptions,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
