/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import type {
	PublishMutationRequest,
	PublishMutationResponse,
} from "../models/Publish.ts";

export const publishMutationKey = () =>
	[{ url: "/api/notifications/publish" }] as const;

export type PublishMutationKey = ReturnType<typeof publishMutationKey>;

/**
 * @summary 알림 발행
 * {@link /api/notifications/publish}
 */
export async function publish(
	data?: PublishMutationRequest,
	config: Partial<RequestConfig<PublishMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		PublishMutationResponse,
		ResponseErrorConfig<Error>,
		PublishMutationRequest
	>({
		method: "POST",
		url: `/api/notifications/publish`,
		data: requestData,
		...requestConfig,
	});
	return res.data;
}

export function publishMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<PublishMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const mutationKey = publishMutationKey();
	return mutationOptions<
		PublishMutationResponse,
		ResponseErrorConfig<Error>,
		{ data?: PublishMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return publish(data, config);
		},
	});
}

/**
 * @summary 알림 발행
 * {@link /api/notifications/publish}
 */
export function usePublish<TContext>(
	options: {
		mutation?: UseMutationOptions<
			PublishMutationResponse,
			ResponseErrorConfig<Error>,
			{ data?: PublishMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig<PublishMutationRequest>> & {
			client?: typeof fetch;
		};
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey = mutationOptions.mutationKey ?? publishMutationKey();

	const baseOptions = publishMutationOptions(config) as UseMutationOptions<
		PublishMutationResponse,
		ResponseErrorConfig<Error>,
		{ data?: PublishMutationRequest },
		TContext
	>;

	return useMutation<
		PublishMutationResponse,
		ResponseErrorConfig<Error>,
		{ data?: PublishMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		PublishMutationResponse,
		ResponseErrorConfig<Error>,
		{ data?: PublishMutationRequest },
		TContext
	>;
}
