/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import type { PollQueryParams, PollQueryResponse } from "../models/Poll.ts";

export const pollSuspenseQueryKey = (params: PollQueryParams = {}) =>
	[{ url: "/api/notifications/poll" }, ...(params ? [params] : [])] as const;

export type PollSuspenseQueryKey = ReturnType<typeof pollSuspenseQueryKey>;

/**
 * @summary 폴링 조회
 * {@link /api/notifications/poll}
 */
export async function pollSuspense(
	params?: PollQueryParams,
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		PollQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: `/api/notifications/poll`,
		params,
		...requestConfig,
	});
	return res.data;
}

export function pollSuspenseQueryOptions(
	params?: PollQueryParams,
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = pollSuspenseQueryKey(params);
	return queryOptions<
		PollQueryResponse,
		ResponseErrorConfig<Error>,
		PollQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return pollSuspense(params, config);
		},
	});
}

/**
 * @summary 폴링 조회
 * {@link /api/notifications/poll}
 */
export function usePollSuspense<
	TData = PollQueryResponse,
	TQueryKey extends QueryKey = PollSuspenseQueryKey,
>(
	params?: PollQueryParams,
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				PollQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? pollSuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{
			...pollSuspenseQueryOptions(params, config),
			queryKey,
			...queryOptions,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
