/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import type { PollQueryParams, PollQueryResponse } from "../models/Poll.ts";

export const pollQueryKey = (params: PollQueryParams = {}) =>
	[{ url: "/api/notifications/poll" }, ...(params ? [params] : [])] as const;

export type PollQueryKey = ReturnType<typeof pollQueryKey>;

/**
 * @summary 폴링 조회
 * {@link /api/notifications/poll}
 */
export async function poll(
	params?: PollQueryParams,
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		PollQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: `/api/notifications/poll`,
		params,
		...requestConfig,
	});
	return res.data;
}

export function pollQueryOptions(
	params?: PollQueryParams,
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = pollQueryKey(params);
	return queryOptions<
		PollQueryResponse,
		ResponseErrorConfig<Error>,
		PollQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return poll(params, config);
		},
	});
}

/**
 * @summary 폴링 조회
 * {@link /api/notifications/poll}
 */
export function usePoll<
	TData = PollQueryResponse,
	TQueryData = PollQueryResponse,
	TQueryKey extends QueryKey = PollQueryKey,
>(
	params?: PollQueryParams,
	options: {
		query?: Partial<
			QueryObserverOptions<
				PollQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? pollQueryKey(params);

	const query = useQuery(
		{
			...pollQueryOptions(params, config),
			queryKey,
			...queryOptions,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
