/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import type { SubscribeQueryResponse } from "../models/Subscribe.ts";

export const subscribeSuspenseQueryKey = () =>
	[{ url: "/api/notifications/subscribe" }] as const;

export type SubscribeSuspenseQueryKey = ReturnType<
	typeof subscribeSuspenseQueryKey
>;

/**
 * @summary SSE 구독
 * {@link /api/notifications/subscribe}
 */
export async function subscribeSuspense(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		SubscribeQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: `/api/notifications/subscribe`, ...requestConfig });
	return res.data;
}

export function subscribeSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = subscribeSuspenseQueryKey();
	return queryOptions<
		SubscribeQueryResponse,
		ResponseErrorConfig<Error>,
		SubscribeQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return subscribeSuspense(config);
		},
	});
}

/**
 * @summary SSE 구독
 * {@link /api/notifications/subscribe}
 */
export function useSubscribeSuspense<
	TData = SubscribeQueryResponse,
	TQueryKey extends QueryKey = SubscribeSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				SubscribeQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? subscribeSuspenseQueryKey();

	const query = useSuspenseQuery(
		{
			...subscribeSuspenseQueryOptions(config),
			queryKey,
			...queryOptions,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
