/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	QueryKey,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";
import type { SubscribeQueryResponse } from "../models/Subscribe.ts";

export const subscribeQueryKey = () =>
	[{ url: "/api/notifications/subscribe" }] as const;

export type SubscribeQueryKey = ReturnType<typeof subscribeQueryKey>;

/**
 * @summary SSE 구독
 * {@link /api/notifications/subscribe}
 */
export async function subscribe(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		SubscribeQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({ method: "GET", url: `/api/notifications/subscribe`, ...requestConfig });
	return res.data;
}

export function subscribeQueryOptions(
	config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
	const queryKey = subscribeQueryKey();
	return queryOptions<
		SubscribeQueryResponse,
		ResponseErrorConfig<Error>,
		SubscribeQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			config.signal = signal;
			return subscribe(config);
		},
	});
}

/**
 * @summary SSE 구독
 * {@link /api/notifications/subscribe}
 */
export function useSubscribe<
	TData = SubscribeQueryResponse,
	TQueryData = SubscribeQueryResponse,
	TQueryKey extends QueryKey = SubscribeQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				SubscribeQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: typeof fetch };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...queryOptions } = queryConfig;
	const queryKey = queryOptions?.queryKey ?? subscribeQueryKey();

	const query = useQuery(
		{
			...subscribeQueryOptions(config),
			queryKey,
			...queryOptions,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
