/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import type {
	UpdateMutationRequest,
	UpdateMutationResponse,
	UpdatePathParams,
} from "../models/Update.ts";

export const updateMutationKey = () => [{ url: "/api/posts/:id" }] as const;

export type UpdateMutationKey = ReturnType<typeof updateMutationKey>;

/**
 * @summary 게시글 수정
 * {@link /api/posts/:id}
 */
export async function update(
	id: UpdatePathParams["id"],
	data: UpdateMutationRequest,
	config: Partial<RequestConfig<UpdateMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		UpdateMutationResponse,
		ResponseErrorConfig<Error>,
		UpdateMutationRequest
	>({
		method: "PUT",
		url: `/api/posts/${id}`,
		data: requestData,
		...requestConfig,
	});
	return res.data;
}

export function updateMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<UpdateMutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const mutationKey = updateMutationKey();
	return mutationOptions<
		UpdateMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: UpdatePathParams["id"]; data: UpdateMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id, data }) => {
			return update(id, data, config);
		},
	});
}

/**
 * @summary 게시글 수정
 * {@link /api/posts/:id}
 */
export function useUpdate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UpdateMutationResponse,
			ResponseErrorConfig<Error>,
			{ id: UpdatePathParams["id"]; data: UpdateMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig<UpdateMutationRequest>> & {
			client?: typeof fetch;
		};
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey = mutationOptions.mutationKey ?? updateMutationKey();

	const baseOptions = updateMutationOptions(config) as UseMutationOptions<
		UpdateMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: UpdatePathParams["id"]; data: UpdateMutationRequest },
		TContext
	>;

	return useMutation<
		UpdateMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: UpdatePathParams["id"]; data: UpdateMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UpdateMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: UpdatePathParams["id"]; data: UpdateMutationRequest },
		TContext
	>;
}
