/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import fetch from "@kubb/plugin-client/clients/axios";
import type {
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import type {
	Update1MutationRequest,
	Update1MutationResponse,
	Update1PathParams,
} from "../models/Update1.ts";

export const update1MutationKey = () => [{ url: "/api/members/:id" }] as const;

export type Update1MutationKey = ReturnType<typeof update1MutationKey>;

/**
 * @summary 회원 수정
 * {@link /api/members/:id}
 */
export async function update1(
	id: Update1PathParams["id"],
	data: Update1MutationRequest,
	config: Partial<RequestConfig<Update1MutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		Update1MutationResponse,
		ResponseErrorConfig<Error>,
		Update1MutationRequest
	>({
		method: "PUT",
		url: `/api/members/${id}`,
		data: requestData,
		...requestConfig,
	});
	return res.data;
}

export function update1MutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<Update1MutationRequest>> & {
		client?: typeof fetch;
	} = {},
) {
	const mutationKey = update1MutationKey();
	return mutationOptions<
		Update1MutationResponse,
		ResponseErrorConfig<Error>,
		{ id: Update1PathParams["id"]; data: Update1MutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id, data }) => {
			return update1(id, data, config);
		},
	});
}

/**
 * @summary 회원 수정
 * {@link /api/members/:id}
 */
export function useUpdate1<TContext>(
	options: {
		mutation?: UseMutationOptions<
			Update1MutationResponse,
			ResponseErrorConfig<Error>,
			{ id: Update1PathParams["id"]; data: Update1MutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig<Update1MutationRequest>> & {
			client?: typeof fetch;
		};
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey = mutationOptions.mutationKey ?? update1MutationKey();

	const baseOptions = update1MutationOptions(config) as UseMutationOptions<
		Update1MutationResponse,
		ResponseErrorConfig<Error>,
		{ id: Update1PathParams["id"]; data: Update1MutationRequest },
		TContext
	>;

	return useMutation<
		Update1MutationResponse,
		ResponseErrorConfig<Error>,
		{ id: Update1PathParams["id"]; data: Update1MutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		Update1MutationResponse,
		ResponseErrorConfig<Error>,
		{ id: Update1PathParams["id"]; data: Update1MutationRequest },
		TContext
	>;
}
