/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MemberRequestDto } from "./MemberRequestDto.ts";
import type { MemberResponseDto } from "./MemberResponseDto.ts";

/**
 * @description Created
 */
export type Create1201 = MemberResponseDto;

export type Create1MutationRequest = MemberRequestDto;

export type Create1MutationResponse = Create1201;

export type Create1Mutation = {
	Response: Create1201;
	Request: Create1MutationRequest;
	Errors: any;
};
