/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PostRequestDto } from "./PostRequestDto.ts";
import type { PostResponseDto } from "./PostResponseDto.ts";

/**
 * @description Created
 */
export type Create201 = PostResponseDto;

export type CreateMutationRequest = PostRequestDto;

export type CreateMutationResponse = Create201;

export type CreateMutation = {
	Response: Create201;
	Request: CreateMutationRequest;
	Errors: any;
};
