/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Delete1PathParams = {
	/**
	 * @type integer, int64
	 */
	id: number;
};

/**
 * @description No Content
 */
export type Delete1204 = any;

export type Delete1MutationResponse = Delete1204;

export type Delete1Mutation = {
	Response: Delete1204;
	PathParams: Delete1PathParams;
	Errors: any;
};
