/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeletePathParams = {
	/**
	 * @type integer, int64
	 */
	id: number;
};

/**
 * @description No Content
 */
export type Delete204 = any;

export type DeleteMutationResponse = Delete204;

export type DeleteMutation = {
	Response: Delete204;
	PathParams: DeletePathParams;
	Errors: any;
};
