/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PostResponseDto } from "./PostResponseDto.ts";

export type FindByIdPathParams = {
	/**
	 * @type integer, int64
	 */
	id: number;
};

/**
 * @description OK
 */
export type FindById200 = PostResponseDto;

export type FindByIdQueryResponse = FindById200;

export type FindByIdQuery = {
	Response: FindById200;
	PathParams: FindByIdPathParams;
	Errors: any;
};
