/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MemberResponseDto } from "./MemberResponseDto.ts";

/**
 * @description OK
 */
export type FindAll1200 = MemberResponseDto[];

export type FindAll1QueryResponse = FindAll1200;

export type FindAll1Query = {
	Response: FindAll1200;
	Errors: any;
};
