/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PostResponseDto } from "./PostResponseDto.ts";

/**
 * @description OK
 */
export type FindAll200 = PostResponseDto[];

export type FindAllQueryResponse = FindAll200;

export type FindAllQuery = {
	Response: FindAll200;
	Errors: any;
};
