/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MemberResponseDto } from "./MemberResponseDto.ts";

export type FindById1PathParams = {
	/**
	 * @type integer, int64
	 */
	id: number;
};

/**
 * @description OK
 */
export type FindById1200 = MemberResponseDto;

export type FindById1QueryResponse = FindById1200;

export type FindById1Query = {
	Response: FindById1200;
	PathParams: FindById1PathParams;
	Errors: any;
};
