/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MemberResponseDto = {
	/**
	 * @type integer | undefined, int64
	 */
	id?: number;
	/**
	 * @type string | undefined
	 */
	name?: string;
	/**
	 * @type string | undefined
	 */
	email?: string;
};
