/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type NotificationDto = {
	/**
	 * @type integer | undefined, int64
	 */
	id?: number;
	/**
	 * @type string | undefined
	 */
	message?: string;
	/**
	 * @type string | undefined, date-time
	 */
	createdAt?: string;
};
