/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { NotificationDto } from "./NotificationDto.ts";

export type PollQueryParams = {
	/**
	 * @default 0
	 * @type integer | undefined, int64
	 */
	lastId?: number;
};

/**
 * @description OK
 */
export type Poll200 = NotificationDto[];

export type PollQueryResponse = Poll200;

export type PollQuery = {
	Response: Poll200;
	QueryParams: PollQueryParams;
	Errors: any;
};
