/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostResponseDto = {
	/**
	 * @type integer | undefined, int64
	 */
	id?: number;
	/**
	 * @type string | undefined
	 */
	title?: string;
	/**
	 * @type string | undefined
	 */
	content?: string;
	/**
	 * @type string | undefined
	 */
	author?: string;
	/**
	 * @type string | undefined, date-time
	 */
	createdAt?: string;
	/**
	 * @type string | undefined, date-time
	 */
	updatedAt?: string;
};
