/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostRequestDto = {
	/**
	 * @minLength 1
	 * @type string
	 */
	title: string;
	/**
	 * @type string | undefined
	 */
	content?: string;
	/**
	 * @type string | undefined
	 */
	author?: string;
};
