/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { NotificationDto } from "./NotificationDto.ts";

/**
 * @description OK
 */
export type Publish200 = NotificationDto;

export type PublishMutationRequest = {
	[key: string]: string;
};

export type PublishMutationResponse = Publish200;

export type PublishMutation = {
	Response: Publish200;
	Request: PublishMutationRequest;
	Errors: any;
};
