/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SseEmitter } from "./SseEmitter.ts";

/**
 * @description OK
 */
export type Subscribe200 = SseEmitter;

export type SubscribeQueryResponse = Subscribe200;

export type SubscribeQuery = {
	Response: Subscribe200;
	Errors: any;
};
