/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PostRequestDto } from "./PostRequestDto.ts";
import type { PostResponseDto } from "./PostResponseDto.ts";

export type UpdatePathParams = {
	/**
	 * @type integer, int64
	 */
	id: number;
};

/**
 * @description OK
 */
export type Update200 = PostResponseDto;

export type UpdateMutationRequest = PostRequestDto;

export type UpdateMutationResponse = Update200;

export type UpdateMutation = {
	Response: Update200;
	Request: UpdateMutationRequest;
	PathParams: UpdatePathParams;
	Errors: any;
};
