/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MemberRequestDto } from "./MemberRequestDto.ts";
import type { MemberResponseDto } from "./MemberResponseDto.ts";

export type Update1PathParams = {
	/**
	 * @type integer, int64
	 */
	id: number;
};

/**
 * @description OK
 */
export type Update1200 = MemberResponseDto;

export type Update1MutationRequest = MemberRequestDto;

export type Update1MutationResponse = Update1200;

export type Update1Mutation = {
	Response: Update1200;
	Request: Update1MutationRequest;
	PathParams: Update1PathParams;
	Errors: any;
};
